version: '3'
services:
  nginx-reverseproxy:
    image: nginx:latest
    container_name: nginx-reverseproxy
    volumes:
      - ./cfg/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cfg/nginx/inc-cfg:/etc/nginx/inc-cfg
      - /certs:/etc/letsencrypt
      - ./cfg/certbot/www-challenge:/var/www/certbot
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    network_mode: "host"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    container_name: nginx-reverseproxy-certbot
    volumes:
    - /certs:/etc/letsencrypt
    - ./cfg/certbot/www-challenge:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 48h & wait $${!}; done;'"
    network_mode: "bridge"
    privileged: true