version: '3'
services:
  nginx-reverseproxy:
    image: nginx:latest
    volumes:
      # Configuration Files for NGINX
      - ./cfg/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cfg/nginx/inc-cfg:/etc/nginx/inc-cfg
      - ./logs/nginx:/var/log/nginx
      # Certificates directory must match with certbot
      - /certs:/etc/letsencrypt
      # LetsEncrypt Challenge directory must be published by NGINX
      - ./cfg/certbot/www-challenge:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    network_mode: "host"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      # Certificates directory must match with certbot
      - /certs:/etc/letsencrypt
      # LetsEncrypt Challenge directory must be published by NGINX
      - ./cfg/certbot/www-challenge:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 48h & wait $${!}; done;'"
    network_mode: "bridge"
