version: '3'
services:
  nginx-reverseproxy:
    image: nginx:latest
    container_name: nginx-reverseproxy
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/services:/etc/nginx/services
      - ./config/backends:/etc/nginx/backends
      - ./config/subdomains:/etc/nginx/subdomains
      - ./config/certs/conf:/etc/letsencrypt
      - ./config/certs/www:/var/www/certbot
      - ./config/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    network_mode: "host"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    container_name: nginx-reverseproxy-certbot
    volumes:
    - ./config/certs/conf:/etc/letsencrypt
    - ./config/certs/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 48h & wait $${!}; done;'"
    network_mode: "bridge"
    privileged: true